### ISSUE TITLE
Could this be added to logistics chests?

### ISSUE THREAD

**Issue by jantzenw** [tfg13/factorio_logistics_requests_sorted#1]
My buffer chests are a big stinky mess of unsorted logistic requests

**Comment by tfg13** [comment]
Oh interesting question. I can try to take a look in the next days. Not sure it is possible, I think chest are different from player and spidertron but I need to dig a bit more to be sure.

**Comment by tfg13** [comment]
Ok so I checked.

Unfortunately I don't see a way to trigger this, there seems to be no event that fires when the logistic requests of chests get manipulated. For the player, I am using https://lua-api.factorio.com/latest/events.html#on_entity_logistic_slot_changed, which explicitly says it is not for chests:
> "Personal logistic slot" refers to a character or vehicle's personal request / auto-trash slots, not the request slots on logistic chests.

I suspect this is because the chest requests are very different, as they can be changed by circuit signals.

**Comment by jantzenw** [comment]
No problem thanks for looking
