### ISSUE TITLE
Reserve and sort slots in player inventory for logistic requests

### ISSUE THREAD

**Issue by Saklad5** [tfg13/factorio_logistics_requests_sorted#2]
I’m not sure how feasible this is, or whether you consider it within the scope of the mod, but I’d like to also have player inventory slots automatically reserved and sorted to receive logistic requests.

In case you don’t know what I am referring to, you can Command-Right-Click on a slot in a character or cargo wagon’s inventory to reserve it for a certain item. This makes that slot (including its position, much like logistic requests without this mod) reserved for only that item.

This is useful for any logistic request, as you need enough room to actually accept things. To be more specific, I’d like the first slots in the player inventory to be reserved, with one slot per stack. For obvious reasons, stacks should only be counted based on the minimum amount for each logistic request.

**Comment by tfg13** [comment]
This is a very interesting idea. I was going to say "can't be done", but then I checked and one can actually set filters for the player inventory, I didn't even know :D

I do feel it is a bit out of scope, almost a separate mod: "Sync Inventory filters with logistics requests".

I need to think about this some more, but I think there might be some edge cases that would need to be worked out:

- What happens if the player manually changes inventory filters? (removing ones created by the mod, adding more, changing slot positions, ...)
- What happens if the inventory is full and a new request is added? If creating new logistics requests can't be prevented in this case (I think this is how it works), this can get out of sync
- How does this interact with unsorted player inventories (you can disable the auto-sorting for the player inventory in the settings)

This is just what comes to mind right now, not sure all of these are an issue.

**Comment by Saklad5** [comment]
Perhaps a separate mod, which sorts all filtered character slots, would be better. That wouldn’t automatically follow logistic requests, but it would avoid the edge cases.

**Comment by tfg13** [comment]
I am going to close this one out, it is a bit out of scope for this mod :)
